MushOS: heap.c File Reference
heap.c File Reference
#include "heap.h"
#include "memory.h"
Functions
static heap_block_header * get_header (void *structure)
u_dword size (void *structure)
static void * allocate_space (void *free_pointer, u_dword size, heap_block_header *previous, heap_block_header *next)
void initialize_heap (void *start_address, u_dword size)
void * malloc (u_dword size)
void * realloc (void *structure, u_dword new_size)
void free (void *structure)
Variables
heap_header * header
Function Documentation
get_header()
static heap_block_header * get_header (void * structure) static
Internal function for getting heap header of any structure located in heap. It just substracts heap block header size from pointer and casts it to heap block header.
Parameters
structure a pointer to the structure.
Returns
heap_block_header pointer.
Definition at line 28 of file heap.c.
{
    return (heap_block_header*) (structure - sizeof(heap_block_header));
}
Referenced by allocate_space(), free(), malloc(), realloc(), and size().
size()
u_dword size (void * structure)
Function for structure located in heap size calculation (in bytes). Throws heap exception if the given pointer is outside of the current heap.
Parameters
structure a pointer to the structure.
Returns
structure size (in bytes).
Definition at line 38 of file heap.c.
{
    if (structure > header->heap_start && structure < header->heap_end) return get_header(structure)->size;
    else ; // TODO: throw exception: requested structure is outside of the heap!
}
References get_header(), header, heap_header::heap_start, and heap_block_header::size.
Referenced by allocate_space(), copy_part(), initialize_heap(), malloc(), and realloc().
allocate_space()
static void * allocate_space (void * free_pointer, u_dword size, heap_block_header * previous, heap_block_header * next) static
Internal function for space allocation in heap. Sets up and fills heap block header, optionally alters headers of the next and previous heap blocks.
Parameters
free_pointer pointer to free space (heap block header size + required size).
size required size of heap block.
previous previous heap block.
next next heap block.
Returns
pointer to the start of the block.
Definition at line 54 of file heap.c.
{
    ((heap_block_header*) free_pointer)->size = size;
    ((heap_block_header*) free_pointer)->previous = previous;
    ((heap_block_header*) free_pointer)->next = next;
    void* memory_address = free_pointer + sizeof(heap_block_header);
    if (previous) get_header(previous)->next = memory_address;
    if (next) get_header(next)->previous = memory_address;
    return memory_address;
}
References get_header(), heap_block_header::next, heap_block_header::previous, and size().
Referenced by malloc().
initialize_heap()
void initialize_heap (void * start_address, u_dword size)
Function for heap initialization, sets up singleton heap header. This implementation of heap has fixed size, and so doesn't rely on paging. That's enough for kernel and basic app needs, TODO: provide another heap implementation for extended MushLib.
Parameters
start_address pointer to the start of the heap.
size size of the heap.
Definition at line 74 of file heap.c.
{
    header = start_address;
    memory_clear(start_address, sizeof(heap_header), 0);
    header->heap_start = start_address + sizeof(heap_header);
    header->heap_end = start_address + size;
    header->first_address = nullptr;
}
References heap_header::first_address, header, heap_header::heap_end, heap_header::heap_start, memory_clear(), and size().
Referenced by _start().
malloc()
void * malloc (u_dword size)
Function for allocation of a heap block. Searches for a place of suitable size to fit a structure of requested size in. Throws heap exception if no free space is available.
Parameters
size requested block size.
Returns
pointer to the neewly allocated block.
Definition at line 89 of file heap.c.
{
    if (header->first_address) {
        void* best_address = nullptr, * best_previous = nullptr, * best_next = nullptr;
        u_dword best_size = header->heap_end - header->heap_start;
        void* current_address = header->heap_start;
        void* next_address = header->first_address;
        u_dword free_space_size = next_address - current_address - sizeof(heap_block_header);
        if ((free_space_size >= (size + sizeof(heap_block_header))) && (free_space_size < best_size)) {
            best_size = free_space_size;
            best_address = current_address; best_previous = nullptr; best_next = next_address;
        }
        current_address = next_address;
        heap_block_header* current_block = get_header(current_address);
        next_address = current_block->next;
        while (next_address) {
            free_space_size = next_address - current_address - current_block->size - sizeof(heap_block_header);
            if ((free_space_size >= (size + sizeof(heap_block_header))) && (free_space_size < best_size)) {
                best_size = free_space_size;
                best_address = current_address + current_block->size; best_previous = current_address; best_next = next_address;
            }
            current_address = next_address;
            current_block = get_header(current_address);
            next_address = current_block->next;
        }
        free_space_size = header->heap_end - current_address - current_block->size - sizeof(heap_block_header);
        if ((free_space_size >= (size + sizeof(heap_block_header))) && (free_space_size < best_size)) {
            best_address = current_address + current_block->size; best_previous = current_address; best_next = nullptr;
        }
        void* final_address = nullptr;
        if (best_address != nullptr) final_address = allocate_space(best_address, size, best_previous, best_next);
        if (best_address == header->heap_start) header->first_address = final_address;
        if (final_address == nullptr) ; // TODO: Throw allocation exception, exception handling in kernel -> panic.
        return final_address;
    } else {
        header->first_address = allocate_space(header->heap_start, size, nullptr, nullptr);
        return header->first_address;
    }
}
References allocate_space(), heap_header::first_address, get_header(), header, heap_header::heap_end, heap_header::heap_start, heap_block_header::next, size(), and heap_block_header::size.
Referenced by get_args(), print_colored(), and realloc().
realloc()
void * realloc (void * structure, u_dword new_size)
Function for heap block size alteration. Attempts to alter size in-place and copys the block only if in-place growth is not available.
Parameters
structure pointer to the structure for reallocation.
new_size new requested size of the structure.
Returns
pointer to the new structure.
Definition at line 143 of file heap.c.
{
    heap_block_header* block = get_header(structure);
    if (new_size < block->size) {
        block->size = new_size;
    } else if (new_size > block->size) {
        if (new_size < block->next - structure) block->size = new_size;
        else {
            void* new_structure = malloc(new_size);
            memory_copy(structure, new_structure, block->size);
            free(structure);
            structure = new_structure;
        }
    }
    return structure;
}
References free(), get_header(), malloc(), memory_copy(), size(), and heap_block_header::size.
free()
void free (void * structure)
Function for heap block freeing.
Parameters
structure pointer to the structure for freeing.
Definition at line 163 of file heap.c.
{
    heap_block_header* block = get_header(structure);
    if (structure == header->first_address) header->first_address = block->next;
    if (block->next) get_header(block->next)->previous = block->previous;
    if (block->previous) get_header(block->previous)->next = block->next;
}
References heap_header::first_address, get_header(), header, heap_block_header::next, and heap_block_header::previous.
Referenced by print_colored(), and realloc().
Variable Documentation
header
heap_header* header
Header of the current app heap. Every app in MushOS has its own heap. This implementation of heap is a singleton.
Definition at line 18 of file heap.c.
Referenced by free(), initialize_heap(), malloc(), and size().