MushOS: interruptions.h File Reference
interruptions.h File Reference
#include "../../lib/base/generic.h"
Macros
#define IRQ0 32
#define IRQ1 33
#define IRQ2 34
#define IRQ3 35
#define IRQ4 36
#define IRQ5 37
#define IRQ6 38
#define IRQ7 39
#define IRQ8 40
#define IRQ9 41
#define IRQ10 42
#define IRQ11 43
#define IRQ12 44
#define IRQ13 45
#define IRQ14 46
#define IRQ15 47
#define DEFAULT_IRS 32
Functions
void isr0 ()
void isr1 ()
void isr2 ()
void isr3 ()
void isr4 ()
void isr5 ()
void isr6 ()
void isr7 ()
void isr8 ()
void isr9 ()
void isr10 ()
void isr11 ()
void isr12 ()
void isr13 ()
void isr14 ()
void isr15 ()
void isr16 ()
void isr17 ()
void isr18 ()
void isr19 ()
void isr20 ()
void isr21 ()
void isr22 ()
void isr23 ()
void isr24 ()
void isr25 ()
void isr26 ()
void isr27 ()
void isr28 ()
void isr29 ()
void isr30 ()
void isr31 ()
void isr32 ()
void idt_flush (u_dword GDT_descriptor_pos)
void irq0 ()
void irq1 ()
void irq2 ()
void irq3 ()
void irq4 ()
void irq5 ()
void irq6 ()
void irq7 ()
void irq8 ()
void irq9 ()
void irq10 ()
void irq11 ()
void irq12 ()
void irq13 ()
void irq14 ()
void irq15 ()
void isr48 ()
void isr49 ()
void isr50 ()
void isr51 ()
void isr52 ()
Macro Definition Documentation
IRQ0
#define IRQ0 32
Definition at line 7 of file interruptions.h.
IRQ1
#define IRQ1 33
Definition at line 8 of file interruptions.h.
IRQ2
#define IRQ2 34
Definition at line 9 of file interruptions.h.
IRQ3
#define IRQ3 35
Definition at line 10 of file interruptions.h.
IRQ4
#define IRQ4 36
Definition at line 11 of file interruptions.h.
IRQ5
#define IRQ5 37
Definition at line 12 of file interruptions.h.
IRQ6
#define IRQ6 38
Definition at line 13 of file interruptions.h.
IRQ7
#define IRQ7 39
Definition at line 14 of file interruptions.h.
IRQ8
#define IRQ8 40
Definition at line 15 of file interruptions.h.
IRQ9
#define IRQ9 41
Definition at line 16 of file interruptions.h.
IRQ10
#define IRQ10 42
Definition at line 17 of file interruptions.h.
IRQ11
#define IRQ11 43
Definition at line 18 of file interruptions.h.
IRQ12
#define IRQ12 44
Definition at line 19 of file interruptions.h.
IRQ13
#define IRQ13 45
Definition at line 20 of file interruptions.h.
IRQ14
#define IRQ14 46
Definition at line 21 of file interruptions.h.
IRQ15
#define IRQ15 47
Definition at line 22 of file interruptions.h.
DEFAULT_IRS
#define DEFAULT_IRS 32
Definition at line 57 of file interruptions.h.
Function Documentation
isr0()
void isr0 ()
Referenced by init_interruptions().
isr1()
void isr1 ()
Referenced by init_interruptions().
isr2()
void isr2 ()
Referenced by init_interruptions().
isr3()
void isr3 ()
Referenced by init_interruptions().
isr4()
void isr4 ()
Referenced by init_interruptions().
isr5()
void isr5 ()
Referenced by init_interruptions().
isr6()
void isr6 ()
Referenced by init_interruptions().
isr7()
void isr7 ()
Referenced by init_interruptions().
isr8()
void isr8 ()
Referenced by init_interruptions().
isr9()
void isr9 ()
Referenced by init_interruptions().
isr10()
void isr10 ()
Referenced by init_interruptions().
isr11()
void isr11 ()
Referenced by init_interruptions().
isr12()
void isr12 ()
Referenced by init_interruptions().
isr13()
void isr13 ()
Referenced by init_interruptions().
isr14()
void isr14 ()
Referenced by init_interruptions().
isr15()
void isr15 ()
Referenced by init_interruptions().
isr16()
void isr16 ()
Referenced by init_interruptions().
isr17()
void isr17 ()
Referenced by init_interruptions().
isr18()
void isr18 ()
Referenced by init_interruptions().
isr19()
void isr19 ()
Referenced by init_interruptions().
isr20()
void isr20 ()
Referenced by init_interruptions().
isr21()
void isr21 ()
Referenced by init_interruptions().
isr22()
void isr22 ()
Referenced by init_interruptions().
isr23()
void isr23 ()
Referenced by init_interruptions().
isr24()
void isr24 ()
Referenced by init_interruptions().
isr25()
void isr25 ()
Referenced by init_interruptions().
isr26()
void isr26 ()
Referenced by init_interruptions().
isr27()
void isr27 ()
Referenced by init_interruptions().
isr28()
void isr28 ()
Referenced by init_interruptions().
isr29()
void isr29 ()
Referenced by init_interruptions().
isr30()
void isr30 ()
Referenced by init_interruptions().
isr31()
void isr31 ()
Referenced by init_interruptions().
isr32()
void isr32 ()
Referenced by init_interruptions().
idt_flush()
void idt_flush (u_dword GDT_descriptor_pos)
Referenced by init_interruptions().
irq0()
void irq0 ()
Referenced by init_interruptions().
irq1()
void irq1 ()
Referenced by init_interruptions().
irq2()
void irq2 ()
Referenced by init_interruptions().
irq3()
void irq3 ()
Referenced by init_interruptions().
irq4()
void irq4 ()
Referenced by init_interruptions().
irq5()
void irq5 ()
Referenced by init_interruptions().
irq6()
void irq6 ()
Referenced by init_interruptions().
irq7()
void irq7 ()
Referenced by init_interruptions().
irq8()
void irq8 ()
Referenced by init_interruptions().
irq9()
void irq9 ()
Referenced by init_interruptions().
irq10()
void irq10 ()
Referenced by init_interruptions().
irq11()
void irq11 ()
Referenced by init_interruptions().
irq12()
void irq12 ()
Referenced by init_interruptions().
irq13()
void irq13 ()
Referenced by init_interruptions().
irq14()
void irq14 ()
Referenced by init_interruptions().
irq15()
void irq15 ()
Referenced by init_interruptions().
isr48()
void isr48 ()
Referenced by init_interruptions().
isr49()
void isr49 ()
Referenced by init_interruptions().
isr50()
void isr50 ()
Referenced by init_interruptions().
isr51()
void isr51 ()
Referenced by init_interruptions().
isr52()
void isr52 ()
Referenced by init_interruptions().