MushOS: keyboard.h File Reference
keyboard.h File Reference
Functions
void init_keyboard ()
Function Documentation
init_keyboard()
void init_keyboard ()
Definition at line 37 of file keyboard.c.
                     {
    set_interrupt_handler(IRQ1, keyboard_callback);
}
References IRQ1, keyboard_callback(), and set_interrupt_handler().
Referenced by _start().