MushOS: memory.h File Reference
memory.h File Reference
#include "generic.h"
Functions
void memory_copy (byte *source, byte *dest, u_dword num_bytes)
void memory_clear (byte *start, u_dword num_bytes, byte sample)
void memory_fill (byte *source, byte *dest, u_dword source_bytes, u_dword times)
boolean memory_compare (byte *comp1, byte *comp2, u_dword length)
Function Documentation
memory_copy()
void memory_copy (byte * source, byte * dest, u_dword num_bytes)
Definition at line 4 of file memory.c.
{
    for (int i = 0; i < num_bytes; ++i) {
        *(dest + i) = *(source + i);
    }
}
Referenced by realloc(), and scroll().
memory_clear()
void memory_clear (byte * start, u_dword num_bytes, byte sample)
Definition at line 10 of file memory.c.
{
    for (int i = 0; i < num_bytes; ++i) {
        *(start + i) = sample;
    }
}
Referenced by allocate_page_table(), get_page(), init_interruptions(), initialise_paging(), and initialize_heap().
memory_fill()
void memory_fill (byte * source, byte * dest, u_dword source_bytes, u_dword times)
Definition at line 16 of file memory.c.
{
    for (int i = 0; i < times; ++i) {
        for (int j = 0; j < source_bytes; ++j) {
            *(dest + (i * source_bytes + j)) = *(source + j);
        }
    }
}
Referenced by clear_screen(), and scroll().
memory_compare()
boolean memory_compare (byte * comp1, byte * comp2, u_dword length)
Definition at line 24 of file memory.c.
{
    boolean equal = true;
    for (int i = 0; i < length; ++i) {
        equal &= (*(comp1 + i) == *(comp2 + i));
    }
    return equal;
}