MushOS: pages.h File Reference
pages.h File Reference
#include "../../lib/base/generic.h"
#include "interruption_tables.h"
Data Structures
struct page_pointer
struct page_table
struct page_table_pointer
struct page_directory
Macros
#define page_size 0x1000
Functions
void initialise_paging ()
void * get_page_address (u_dword address)
void page_fault (registers *regs)
Macro Definition Documentation
page_size
#define page_size 0x1000
Definition at line 9 of file pages.h.
Function Documentation
initialise_paging()
void initialise_paging ()
Sets up the environment, page directories etc and enables paging.
Definition at line 248 of file pages.c.
{
    // The size of physical memory. For the moment we
    // assume it is 16MB big.
    u_dword page_pool_size = (memory_end - orbit_start) / page_size / 8;
    page_pool = k_malloc_aligned(page_pool_size, false);
    memory_clear((byte*) page_pool, page_pool_size, 0);
    u_dword page_table_pool_size = (page_dirs - page_tables) / sizeof(page_table) / 8;
    page_pool = k_malloc_aligned(page_table_pool_size, false);
    memory_clear((byte*) page_pool, page_table_pool_size, 0);
    // Let's make a page directory.
    kernel_directory = (page_directory*) k_malloc_aligned(sizeof(page_directory), true);
    memory_clear((byte*) kernel_directory, sizeof(page_directory), 0);
    for (u_dword j = 0; j < orbit_start; j += page_size)
        *get_page(j, 0x00000003, kernel_directory) = create_page_entry((const byte*) j, 0x00000003);
    for (u_dword j = memory_end; j < memory_edge; j += page_size)
        *get_page(j, 0x00000003, kernel_directory) = create_page_entry((const byte*) j, 0x00000003);
    // Before we enable paging, we must register our page fault handler.
    set_interrupt_handler(14, page_fault);
    current_directory = kernel_directory;
    // Now, enable paging!
    asm volatile("mov %0, %%cr3":: "r"(&current_directory->tablesPhysical));
    u_dword cr0, cr3;
    asm volatile("mov %%cr3, %0": "=r"(cr3));
    asm volatile("mov %%cr0, %0": "=r"(cr0));
    cr0 |= 0x80000001; // Enable paging!
    asm volatile("mov %0, %%cr0":: "r"(cr0));
}
References create_page_entry(), current_directory, get_page(), k_malloc_aligned(), kernel_directory, memory_clear(), memory_edge, memory_end, orbit_start, page_dirs, page_fault(), page_pool, page_size, page_tables, set_interrupt_handler(), and page_directory::tablesPhysical.
Referenced by _start().
get_page_address()
void * get_page_address (u_dword address)
Definition at line 238 of file pages.c.
{
    page_pointer* ptr = get_page((u_dword) address, 0x00000003, current_directory);
    if (ptr) {
        *ptr = create_page_entry((const byte*) address, 0x00000003);
        return (u_dword*) get_page_pointer(*ptr);
    } else return nullptr;
}
References create_page_entry(), current_directory, get_page(), and get_page_pointer().
page_fault()
void page_fault (registers * regs)
Handler for page faults.
Definition at line 284 of file pages.c.
{
    // A page fault has occurred.
    // The faulting address is stored in the CR2 register.
    u_dword faulting_address;
    asm ("mov %%cr2, %0" : "=r" (faulting_address));
    // The error code gives us details of what happened.
    int present = regs->err_code & 0x1;      // Page not present
    int rw = regs->err_code & 0x2;           // Write operation?
    int us = regs->err_code & 0x4;           // Processor was in user-mode?
    int reserved = regs->err_code & 0x8;     // Overwritten CPU-reserved bits of page entry?
    int id = regs->err_code & 0x10;          // Caused by an instruction fetch?
    // Output an error message.
    bad("Page fault! ( ")
    if (present) bad("present ")
    if (!rw) bad("read-only ")
    if (us) bad("user-mode ")
    if (reserved) bad("reserved ")
    bad(") at %h (EIP: %h)\n", faulting_address, regs->eip)
    asm("jmp .");
}
References bad, registers::eip, and registers::err_code.
Referenced by initialise_paging().