MushOS: placement.h File Reference
placement.h File Reference
#include "../../lib/base/generic.h"
Functions
void * k_malloc (u_dword sz)
void * k_malloc_aligned (u_dword sz, boolean align)
void * k_malloc_physical (u_dword sz, boolean align, u_dword *phys)
Function Documentation
k_malloc()
void * k_malloc (u_dword sz)
Definition at line 24 of file placement.c.
{
    return k_malloc_physical(sz, false, nullptr);
}
References k_malloc_physical().
Referenced by load_module().
k_malloc_aligned()
void * k_malloc_aligned (u_dword sz, boolean align)
Definition at line 20 of file placement.c.
{
    return k_malloc_physical(sz, align, nullptr);
}
References k_malloc_physical().
Referenced by get_page(), init_interruptions(), and initialise_paging().
k_malloc_physical()
void * k_malloc_physical (u_dword sz, boolean align, u_dword * phys)
Definition at line 9 of file placement.c.
{
    if (align && (placement_address & 0x00000fff)) { // If the address is not already page-aligned, align it.
        placement_address &= 0xfffff000;
        placement_address += 0x1000;
    }
    if (phys) *phys = placement_address;
    u_dword tmp = placement_address;
    placement_address += sz;
    return (void*) tmp;
}
References placement_address.
Referenced by k_malloc(), and k_malloc_aligned().