MushOS: ports_io.h File Reference
ports_io.h File Reference
#include "../../lib/base/generic.h"
Functions
byte port_byte_in (u_word port)
void port_byte_out (u_word port, byte data)
u_word port_word_in (u_word port)
void port_word_out (u_word port, u_word data)
Function Documentation
port_byte_in()
byte port_byte_in (u_word port)
Referenced by get_cursor_offset(), init_interruptions(), and keyboard_callback().
port_byte_out()
void port_byte_out (u_word port, byte data)
Referenced by get_cursor_offset(), init_interruptions(), init_timer(), irq_handler(), and set_cursor_offset().
port_word_in()
u_word port_word_in (u_word port)
port_word_out()
void port_word_out (u_word port, u_word data)