MushOS: screen.c File Reference
screen.c File Reference
#include "screen.h"
#include "../../lib/base/generic.h"
#include "../../lib/base/memory.h"
#include "../../lib/base/syscall.h"
#include "../kernel/interruption_tables.h"
#include "ports_io.h"
Data Structures
struct screen_coords
Macros
#define REG_SCREEN_CTRL 0x3d4
#define REG_SCREEN_DATA 0x3d5
#define VIDEO_MEMORY 0xb8000
#define BLACK 0u
#define LIGHT_GRAY 7u
#define ROWS_NUM 25
#define COLS_NUM 80
Enumerations
enum call_type {
GET_CHAR = 0 , SET_CHAR = 1 , SET_CHARS = 2 , GET_CURSOR = 3 ,
SET_CURSOR = 4 , CLEAR_SCREEN = 5
}
Functions
static u_dword get_cursor_offset ()
static void set_cursor_offset (u_dword offset)
static screen_coords get_cursor ()
static void set_cursor (screen_coords coords)
static u_dword scroll (u_dword cursor_offset)
void print_char_color (char c, byte text_color, byte back_color)
char get_char (screen_coords coords)
void print_string_color (string str, byte text_color, byte back_color, u_dword length)
void clear_screen ()
static void screen_callback (registers *regs)
void init_screen_io ()
Macro Definition Documentation
REG_SCREEN_CTRL
#define REG_SCREEN_CTRL 0x3d4
Definition at line 12 of file screen.c.
REG_SCREEN_DATA
#define REG_SCREEN_DATA 0x3d5
Definition at line 13 of file screen.c.
VIDEO_MEMORY
#define VIDEO_MEMORY 0xb8000
Definition at line 15 of file screen.c.
BLACK
#define BLACK 0u
Definition at line 17 of file screen.c.
LIGHT_GRAY
#define LIGHT_GRAY 7u
Definition at line 18 of file screen.c.
ROWS_NUM
#define ROWS_NUM 25
Definition at line 20 of file screen.c.
COLS_NUM
#define COLS_NUM 80
Definition at line 21 of file screen.c.
Enumeration Type Documentation
call_type
enum call_type
Enumerator
GET_CHAR
SET_CHAR
SET_CHARS
GET_CURSOR
SET_CURSOR
CLEAR_SCREEN
Definition at line 127 of file screen.c.
             {
    GET_CHAR = 0, SET_CHAR = 1, SET_CHARS = 2, GET_CURSOR = 3, SET_CURSOR = 4, CLEAR_SCREEN = 5
} call_type;
Function Documentation
get_cursor_offset()
static u_dword get_cursor_offset () static
Definition at line 30 of file screen.c.
{
    port_byte_out(REG_SCREEN_CTRL, 14);
    u_dword offset = (u_dword) ((port_byte_in(REG_SCREEN_DATA) << 8) & 0xff00);
    port_byte_out(REG_SCREEN_CTRL, 15);
    offset += (u_dword) (port_byte_in(REG_SCREEN_DATA) & 0x00ff);
    return offset;
}
References port_byte_in(), port_byte_out(), REG_SCREEN_CTRL, and REG_SCREEN_DATA.
Referenced by get_cursor(), print_char_color(), and screen_callback().
set_cursor_offset()
static void set_cursor_offset (u_dword offset) static
Definition at line 38 of file screen.c.
{
    //if (offset > COLS_NUM * ROWS_NUM) return; FIXME simple check not working.
    port_byte_out(REG_SCREEN_CTRL, 14);
    port_byte_out(REG_SCREEN_DATA, (byte) ((offset & 0xff00) >> 8));
    port_byte_out(REG_SCREEN_CTRL, 15);
    port_byte_out(REG_SCREEN_DATA, (byte) (offset & 0x00ff));
}
References port_byte_out(), REG_SCREEN_CTRL, and REG_SCREEN_DATA.
Referenced by print_char_color(), screen_callback(), and set_cursor().
get_cursor()
static screen_coords get_cursor () static
Definition at line 46 of file screen.c.
{
    u_dword offset = get_cursor_offset();
    return (screen_coords) {offset % COLS_NUM + 1, offset / COLS_NUM};
}
References COLS_NUM, and get_cursor_offset().
set_cursor()
static void set_cursor (screen_coords coords) static
Definition at line 51 of file screen.c.
{
    set_cursor_offset(coords.row * COLS_NUM + coords.column);
}
References COLS_NUM, screen_coords::column, screen_coords::row, and set_cursor_offset().
Referenced by clear_screen().
scroll()
static u_dword scroll (u_dword cursor_offset) static
Definition at line 57 of file screen.c.
{
    if (cursor_offset < COLS_NUM * ROWS_NUM * 2) return cursor_offset;
    for (int i = 1; i < ROWS_NUM; ++i) {
        byte* curr_row = (byte*) VIDEO_MEMORY + (i * COLS_NUM * 2);
        byte* prev_row = (byte*) VIDEO_MEMORY + ((i - 1) * COLS_NUM * 2);
        memory_copy(curr_row, prev_row, COLS_NUM * 2);
    }
    byte* last = (byte*) VIDEO_MEMORY + ((ROWS_NUM - 1) * COLS_NUM * 2);
    u_word sample = (BLACK << 12u) + (LIGHT_GRAY << 8u) + ' ';
    memory_fill(last, (byte *) &sample, 2, COLS_NUM);
    cursor_offset -= COLS_NUM * 2;
    return cursor_offset;
}
References BLACK, COLS_NUM, LIGHT_GRAY, memory_copy(), memory_fill(), ROWS_NUM, and VIDEO_MEMORY.
Referenced by print_char_color().
print_char_color()
void print_char_color (char c, byte text_color, byte back_color)
Definition at line 76 of file screen.c.
{
    byte attributes = (back_color << 4u) + text_color;
    byte* vm = (byte*) VIDEO_MEMORY;
    u_dword mem_offset = get_cursor_offset() * 2;
    if (c == '\n') {
        u_dword rows = (mem_offset / 2) / COLS_NUM + 1;
        mem_offset = 2 * COLS_NUM * rows - 2;
    } else if (c == '\b') {
        mem_offset -= 2;
        vm[mem_offset] = ' ';
        vm[mem_offset + 1] = attributes;
        mem_offset -= 2;
    } else if (c == '\t') {
        for (int i = 0; i < 4; ++i) {
            vm[mem_offset + (2 * i)] = ' ';
            vm[mem_offset + (2 * i) + 1] = attributes;
        }
        mem_offset += 6;
    } else {
        vm[mem_offset] = c;
        vm[mem_offset + 1] = attributes;
    }
    mem_offset += 2;
    mem_offset = scroll(mem_offset);
    set_cursor_offset(mem_offset / 2);
}
References COLS_NUM, get_cursor_offset(), scroll(), set_cursor_offset(), and VIDEO_MEMORY.
Referenced by print_string_color(), and screen_callback().
get_char()
char get_char (screen_coords coords)
Definition at line 105 of file screen.c.
{
    byte* vm = (byte*) VIDEO_MEMORY;
    return vm[coords.row * coords.column];
}
References screen_coords::column, screen_coords::row, and VIDEO_MEMORY.
Referenced by screen_callback().
print_string_color()
void print_string_color (string str, byte text_color, byte back_color, u_dword length)
Definition at line 112 of file screen.c.
{
    if (length == 0) for (int i = 0; str[i] != 0; ++i) print_char_color(str[i], text_color, back_color);
    else for (int i = 0; i < length; ++i) print_char_color(str[i], text_color, back_color);
}
References print_char_color().
Referenced by screen_callback().
clear_screen()
void clear_screen ()
Definition at line 119 of file screen.c.
                    {
    u_word sample = (BLACK << 12) + (LIGHT_GRAY << 8) + ' ';
    memory_fill((byte*) VIDEO_MEMORY, (byte *) &sample, 2, COLS_NUM * ROWS_NUM);
    set_cursor((screen_coords) {0, 0});
}
References BLACK, COLS_NUM, LIGHT_GRAY, memory_fill(), ROWS_NUM, set_cursor(), and VIDEO_MEMORY.
Referenced by screen_callback().
screen_callback()
static void screen_callback (registers * regs) static
Definition at line 131 of file screen.c.
{
    u_dword call_type, ret_value = 0;
    orbital_get_arg(regs->ebp, 0, call_type)
    switch (call_type) {
        case GET_CHAR: {
            ret_value = get_char((screen_coords) {0, 0});
            break;
        }
        case SET_CHAR: {
            u_dword character, front_color, back_color;
            orbital_get_arg(regs->ebp, 1, character)
            orbital_get_arg(regs->ebp, 2, front_color)
            orbital_get_arg(regs->ebp, 3, back_color)
            print_char_color(character, front_color, back_color);
            break;
        }
        case SET_CHARS: {
            u_dword str, front_color, back_color, length;
            orbital_get_arg(regs->ebp, 1, str)
            orbital_get_arg(regs->ebp, 2, front_color)
            orbital_get_arg(regs->ebp, 3, back_color)
            orbital_get_arg(regs->ebp, 4, length)
            print_string_color((mod_string) str, front_color, back_color, length);
        }
        case GET_CURSOR: {
            ret_value = get_cursor_offset();
            break;
        }
        case SET_CURSOR: {
            u_dword offset;
            orbital_get_arg(regs->ebp, 1, offset)
            set_cursor_offset(offset);
            break;
        }
        case CLEAR_SCREEN:
            clear_screen();
            break;
        default:
            break;
    }
    orbital_push(regs->ebp, ret_value)
}
References clear_screen(), CLEAR_SCREEN, registers::ebp, get_char(), GET_CHAR, GET_CURSOR, get_cursor_offset(), orbital_get_arg, orbital_push, print_char_color(), print_string_color(), SET_CHAR, SET_CHARS, SET_CURSOR, and set_cursor_offset().
Referenced by init_screen_io().
init_screen_io()
void init_screen_io ()
Definition at line 176 of file screen.c.
                      {
    set_interrupt_handler(48, screen_callback);
}
References screen_callback(), and set_interrupt_handler().
Referenced by _start().