MushOS: screen.h File Reference
screen.h File Reference
Functions
void clear_screen ()
void init_screen_io ()
Function Documentation
clear_screen()
void clear_screen ()
Definition at line 119 of file screen.c.
                    {
    u_word sample = (BLACK << 12) + (LIGHT_GRAY << 8) + ' ';
    memory_fill((byte*) VIDEO_MEMORY, (byte *) &sample, 2, COLS_NUM * ROWS_NUM);
    set_cursor((screen_coords) {0, 0});
}
References BLACK, COLS_NUM, LIGHT_GRAY, memory_fill(), ROWS_NUM, set_cursor(), and VIDEO_MEMORY.
Referenced by screen_callback().
init_screen_io()
void init_screen_io ()
Definition at line 176 of file screen.c.
                      {
    set_interrupt_handler(48, screen_callback);
}
References screen_callback(), and set_interrupt_handler().
Referenced by _start().