MushOS: stdio.h File Reference
stdio.h File Reference
#include "generic.h"
Macros
#define bad(temp, args...) print_colored(HIGH_RED, BLACK, temp, ## args);
#define warn(temp, args...) print_colored(YELLOW, BLACK, temp, ## args);
#define good(temp, args...) print_colored(HIGH_GREEN, BLACK, temp, ## args);
#define info(temp, args...) print_colored(HIGH_BLUE, BLACK, temp, ## args);
#define plain(temp, args...) print_colored(LIGHT_GRAY, BLACK, temp, ## args);
#define locate(text, back) print_colored(text, back, "%s - %d: ", __FILE__, __LINE__);
#define error(temp, args...) {locate(HIGH_RED, BLACK) bad(temp, ## args)}
#define warning(temp, args...) {locate(YELLOW, BLACK) warn(temp, ## args)}
Enumerations
enum console_color {
BLACK = 0u , LOW_BLUE = 1u , LOW_GREEN = 2u , LOW_CYAN = 3u ,
LOW_RED = 4u , LOW_MAGENTA = 5u , BROWN = 6u , LIGHT_GRAY = 7u ,
DARK_GRAY = 8u , HIGH_BLUE = 9u , HIGH_GREEN = 10u , HIGH_CYAN = 11u ,
HIGH_RED = 12u , HIGH_MAGENTA = 13u , YELLOW = 14u , WHITE = 15u
}
Functions
void print_colored (console_color font, console_color back, string format,...)
Macro Definition Documentation
bad
#define bad (temp, args...) print_colored(HIGH_RED, BLACK, temp, ## args);
Definition at line 30 of file stdio.h.
warn
#define warn (temp, args...) print_colored(YELLOW, BLACK, temp, ## args);
Definition at line 31 of file stdio.h.
good
#define good (temp, args...) print_colored(HIGH_GREEN, BLACK, temp, ## args);
Definition at line 32 of file stdio.h.
info
#define info (temp, args...) print_colored(HIGH_BLUE, BLACK, temp, ## args);
Definition at line 33 of file stdio.h.
plain
#define plain (temp, args...) print_colored(LIGHT_GRAY, BLACK, temp, ## args);
Definition at line 34 of file stdio.h.
locate
#define locate (text, back) print_colored(text, back, "%s - %d: ", __FILE__, __LINE__);
Definition at line 36 of file stdio.h.
error
#define error (temp, args...) {locate(HIGH_RED, BLACK) bad(temp, ## args)}
Definition at line 38 of file stdio.h.
warning
#define warning (temp, args...) {locate(YELLOW, BLACK) warn(temp, ## args)}
Definition at line 39 of file stdio.h.
Enumeration Type Documentation
console_color
enum console_color
Enumerator
BLACK
LOW_BLUE
LOW_GREEN
LOW_CYAN
LOW_RED
LOW_MAGENTA
BROWN
LIGHT_GRAY
DARK_GRAY
HIGH_BLUE
HIGH_GREEN
HIGH_CYAN
HIGH_RED
HIGH_MAGENTA
YELLOW
WHITE
Definition at line 7 of file stdio.h.
             {
    BLACK        = 0u,
    LOW_BLUE     = 1u,
    LOW_GREEN    = 2u,
    LOW_CYAN     = 3u,
    LOW_RED      = 4u,
    LOW_MAGENTA  = 5u,
    BROWN        = 6u,
    LIGHT_GRAY   = 7u,
    DARK_GRAY    = 8u,
    HIGH_BLUE    = 9u,
    HIGH_GREEN   = 10u,
    HIGH_CYAN    = 11u,
    HIGH_RED     = 12u,
    HIGH_MAGENTA = 13u,
    YELLOW       = 14u,
    WHITE        = 15u
} console_color;
Function Documentation
print_colored()
void print_colored (console_color font, console_color back, string format, ...)
Definition at line 102 of file stdio.c.
{
    u_dword temps = 0, length = 0;
    while (format[length]) {
        if (format[length] == '%') temps++;
        length++;
    }
    if (temps == 0) {
        print_text(format, font, back);
        return;
    }
    u_dword* args = (u_dword*) malloc(temps * sizeof(u_dword));
    args_init_from(args, sizeof(console_color) * 2 + sizeof(string))
    u_dword argumentor = 0, printed = 0;
    for (int j = 0; j < length; ++j) {
        if (format[j] == '%') {
            print_n_text(format + printed, font, back, j - printed);
            printed = j + 2;
            j++;
            switch (format[j]) {
                case 'l':
                    print_boolean(args[argumentor], font, back);
                    break;
                case 'p':
                    print_pointer(args[argumentor], font, back);
                    break;
                case 'd':
                    print_number(args[argumentor], INTEGER, DECIMAL, font, back);
                    break;
                case 'h':
                    print_number(args[argumentor], INTEGER, HEXADECIMAL, font, back);
                    break;
                case 'b':
                    print_number(args[argumentor], INTEGER, BINARY, font, back);
                    break;
                case 'f':
                    print_number(args[argumentor], FLOAT, DECIMAL, font, back);
                    break;
                case 'c':
                    print_char(args[argumentor], font, back);
                    break;
                case 's':
                    print_text((string) args[argumentor], font, back);
                    break;
                default:
                    argumentor--;
                    j--;
                    printed -= 2;
                    break;
            }
            argumentor++;
        }
    }
    print_n_text(format + printed, font, back, length - printed);
    free(args);
}
References args_init_from, BINARY, DECIMAL, FLOAT, free(), HEXADECIMAL, INTEGER, malloc(), print_boolean(), print_char(), print_n_text(), print_number(), print_pointer(), and print_text().
Referenced by print_number().