MushOS: stdio.c File Reference
stdio.c File Reference
#include "stdio.h"
#include "heap.h"
#include "vararg.h"
#include "syscall.h"
Macros
#define undefined '?'
Enumerations
enum system { DECIMAL = 10 , HEXADECIMAL = 16 , BINARY = 2 }
enum type { INTEGER , FLOAT }
Functions
void print_char (char c, console_color front, console_color back)
void print_text (string str, byte text_color, byte back_color)
void print_n_text (string str, byte text_color, byte back_color, u_dword length)
static void print_atom (u_byte b, u_dword front, u_dword back, system sys)
static void print_int (u_dword b, u_dword front, u_dword back, system sys)
static void print_float (float b, u_dword front, u_dword back, system sys, u_dword after_comma)
static void print_boolean (boolean b, u_dword front, u_dword back)
static void print_pointer (u_dword b, u_dword front, u_dword back)
void print_number (dword num, type t, system sys, u_dword front, u_dword back)
void print_colored (console_color font, console_color back, string format,...)
Macro Definition Documentation
undefined
#define undefined '?'
Definition at line 8 of file stdio.c.
Enumeration Type Documentation
system
enum system
Enumerator
DECIMAL
HEXADECIMAL
BINARY
Definition at line 10 of file stdio.c.
             {
    DECIMAL = 10, HEXADECIMAL = 16, BINARY = 2
} system;
type
enum type
Enumerator
INTEGER
FLOAT
Definition at line 14 of file stdio.c.
             {
    INTEGER, FLOAT
} type;
Function Documentation
print_char()
void print_char (char c, console_color front, console_color back)
Definition at line 20 of file stdio.c.
{
    call_orbit(48, 4, 1, c, front, back)
}
References call_orbit.
Referenced by print_atom(), print_colored(), print_float(), print_number(), and print_pointer().
print_text()
void print_text (string str, byte text_color, byte back_color)
Definition at line 24 of file stdio.c.
{
    call_orbit(48, 5, 2, str, text_color, back_color, 0)
}
References call_orbit.
Referenced by print_boolean(), print_colored(), print_number(), and print_pointer().
print_n_text()
void print_n_text (string str, byte text_color, byte back_color, u_dword length)
Definition at line 28 of file stdio.c.
{
    if (length > 0) call_orbit(48, 5, 2, str, text_color, back_color, length)
}
References call_orbit.
Referenced by print_colored().
print_atom()
static void print_atom (u_byte b, u_dword front, u_dword back, system sys) static
Definition at line 32 of file stdio.c.
{
    if ((sys >= 2) && (sys <= 10)) print_char(b + 48, front, back);
    else if ((sys > 10) && (sys <= 36)) {
        if (b < 10) print_char(b + 48, front, back);
        else print_char(b + 65 - 10, front, back);
    } else print_char(undefined, front, back);
}
References print_char(), and undefined.
Referenced by print_float(), print_int(), and print_number().
print_int()
static void print_int (u_dword b, u_dword front, u_dword back, system sys) static
Definition at line 40 of file stdio.c.
{
    if (b) {
        byte symbol = b % sys;
        print_int(b / sys, front, back, sys);
        print_atom(symbol, front, back, sys);
    }
}
References print_atom(), and print_int().
Referenced by print_int(), print_number(), and print_pointer().
print_float()
static void print_float (float b, u_dword front, u_dword back, system sys, u_dword after_comma) static
Definition at line 48 of file stdio.c.
{
    if (after_comma) {
        if (b > 1) {
            byte symbol = (u_dword) b % sys;
            print_float(b / (float) sys, front, back, sys, 4);
            print_atom(symbol, front, back, sys);
            if (b / (float) sys < 1) print_char('.', front, back);
        } else if (b) {
            b *= (float) sys;
            byte symbol = (u_dword) b % sys;
            print_float(b / (float) sys, front, back, sys, after_comma - 1);
            print_atom(symbol, front, back, sys);
        }
    }
}
References print_atom(), print_char(), and print_float().
Referenced by print_float(), and print_number().
print_boolean()
static void print_boolean (boolean b, u_dword front, u_dword back) static
Definition at line 64 of file stdio.c.
{
    if (b) print_text("true", front, back);
    else print_text("false", front, back);
}
References print_text().
Referenced by print_colored().
print_pointer()
static void print_pointer (u_dword b, u_dword front, u_dword back) static
Definition at line 69 of file stdio.c.
{
    print_char('.', front, back);
    if (b == nullptr) print_text("null", front, back);
    else print_int(b, front, back, HEXADECIMAL);
}
References HEXADECIMAL, print_char(), print_int(), and print_text().
Referenced by print_colored().
print_number()
void print_number (dword num, type t, system sys, u_dword front, u_dword back)
Definition at line 75 of file stdio.c.
{
    switch (sys) {
        case DECIMAL:
            break;
        case HEXADECIMAL:
            print_text("0x", front, back);
            break;
        case BINARY:
            print_text("0b", front, back);
            break;
        default:
            print_colored(front, back, "(base %d) ", sys);
    }
    if (num == 0) print_atom(0, front, back, sys);
    else if (num < 0) {
        print_char('-', front, back);
        if (t == INTEGER) print_int(-num, front, back, sys);
        else print_float(-num, front, back, sys, 4);
    } else {
        if (t == INTEGER) print_int(num, front, back, sys);
        else print_float(num, front, back, sys, 4);
    }
}
References BINARY, DECIMAL, HEXADECIMAL, INTEGER, print_atom(), print_char(), print_colored(), print_float(), print_int(), and print_text().
Referenced by print_colored().
print_colored()
void print_colored (console_color font, console_color back, string format, ...)
Definition at line 102 of file stdio.c.
{
    u_dword temps = 0, length = 0;
    while (format[length]) {
        if (format[length] == '%') temps++;
        length++;
    }
    if (temps == 0) {
        print_text(format, font, back);
        return;
    }
    u_dword* args = (u_dword*) malloc(temps * sizeof(u_dword));
    args_init_from(args, sizeof(console_color) * 2 + sizeof(string))
    u_dword argumentor = 0, printed = 0;
    for (int j = 0; j < length; ++j) {
        if (format[j] == '%') {
            print_n_text(format + printed, font, back, j - printed);
            printed = j + 2;
            j++;
            switch (format[j]) {
                case 'l':
                    print_boolean(args[argumentor], font, back);
                    break;
                case 'p':
                    print_pointer(args[argumentor], font, back);
                    break;
                case 'd':
                    print_number(args[argumentor], INTEGER, DECIMAL, font, back);
                    break;
                case 'h':
                    print_number(args[argumentor], INTEGER, HEXADECIMAL, font, back);
                    break;
                case 'b':
                    print_number(args[argumentor], INTEGER, BINARY, font, back);
                    break;
                case 'f':
                    print_number(args[argumentor], FLOAT, DECIMAL, font, back);
                    break;
                case 'c':
                    print_char(args[argumentor], font, back);
                    break;
                case 's':
                    print_text((string) args[argumentor], font, back);
                    break;
                default:
                    argumentor--;
                    j--;
                    printed -= 2;
                    break;
            }
            argumentor++;
        }
    }
    print_n_text(format + printed, font, back, length - printed);
    free(args);
}
References args_init_from, BINARY, DECIMAL, FLOAT, free(), HEXADECIMAL, INTEGER, malloc(), print_boolean(), print_char(), print_n_text(), print_number(), print_pointer(), and print_text().
Referenced by print_number().