MushOS: string.c File Reference
string.c File Reference
#include "string.h"
Functions
int len (string str)
void copy_part (string str, mod_string storage, int size)
int first_pos (string str, char ch)
int last_pos (string str, char ch)
boolean equals (string str1, string str2)
void substring_beg (string str, mod_string substr, int begin)
void substring_mid (string str, mod_string substr, int begin, int end)
void substring_end (string str, mod_string substr, int end)
void copy_mod (string str, mod_string m_str)
void move_string_by (mod_string str, int step)
void concatenate (string str1, string str2, mod_string result)
Function Documentation
len()
int len (string str)
Definition at line 4 of file string.c.
                    {
    int string_iterator = 0;
    while (str[string_iterator] != 0) string_iterator++;
    return string_iterator;
}
Referenced by concatenate(), last_pos(), and substring_beg().
copy_part()
void copy_part (string str, mod_string storage, int size)
Definition at line 10 of file string.c.
{
    boolean source_end_reached = false;
    for (int i = 0; i < size; ++i) {
        source_end_reached |= str[i] == 0;
        if (source_end_reached) storage[i] = 0;
        else storage[i] = str[i];
    }
    storage[size] = 0;
}
References size().
first_pos()
int first_pos (string str, char ch)
Definition at line 22 of file string.c.
{
    int string_iterator = 0;
    while (str[string_iterator] != 0) {
        if (str[string_iterator] == ch) return string_iterator;
        string_iterator++;
    }
    return -1;
}
last_pos()
int last_pos (string str, char ch)
Definition at line 31 of file string.c.
{
    int string_iterator = len(str);
    while (string_iterator != 0) {
        if (str[string_iterator] == ch) return string_iterator;
        string_iterator--;
    }
    return -1;
}
References len().
equals()
boolean equals (string str1, string str2)
Definition at line 42 of file string.c.
{
    int string_iterator = 0;
    while ((str1[string_iterator] != 0) && (str2[string_iterator] != 0)) {
        if (str1[string_iterator] == str2[string_iterator]) string_iterator++;
        else return false;
    }
    if ((str1[string_iterator] == 0) && (str2[string_iterator] == 0)) return true;
    else return false;
}
substring_beg()
void substring_beg (string str, mod_string substr, int begin)
Definition at line 54 of file string.c.
{
    substring_mid(str, substr, begin, len(str));
}
References len(), and substring_mid().
substring_mid()
void substring_mid (string str, mod_string substr, int begin, int end)
Definition at line 58 of file string.c.
{
    for (int i = begin; i < end; ++i) substr[i - begin] = str[i];
    substr[end - begin] = 0;
}
Referenced by substring_beg(), and substring_end().
substring_end()
void substring_end (string str, mod_string substr, int end)
Definition at line 63 of file string.c.
{
    substring_mid(str, substr, 0, end);
}
References substring_mid().
copy_mod()
void copy_mod (string str, mod_string m_str)
Definition at line 69 of file string.c.
{
    int i = -1;
    do {
        i++;
        m_str[i] = str[i];
    } while (str[i] != 0);
}
move_string_by()
void move_string_by (mod_string str, int step)
Definition at line 77 of file string.c.
{
    int i = step - 1;
    do {
        i++;
        str[i - step] = str[i];
    } while (str[i] != 0);
}
concatenate()
void concatenate (string str1, string str2, mod_string result)
Definition at line 87 of file string.c.
{
    int str1_length = len(str1), str2_length = len(str2);
    for (int i = 0; i < str1_length; ++i) result[i] = str1[i];
    for (int i = 0; i <= str2_length; ++i) result[i + str1_length] = str2[i];
}
References len().