MushOS: timer.h File Reference
timer.h File Reference
#include "../../lib/base/generic.h"
Functions
void init_timer (u_dword frequency)
Function Documentation
init_timer()
void init_timer (u_dword frequency)
Definition at line 18 of file timer.c.
{
    // Firstly, register our timer callback.
    set_interrupt_handler(IRQ0, &timer_callback);
    // The value we send to the PIT is the value to divide it's input clock
    // (1193180 Hz) by, to get our required frequency. Important to note is
    // that the divisor must be small enough to fit into 16-bits.
    u_dword divisor = 1193180 / frequency;
    // Send the command byte.
    port_byte_out(0x43, 0x36);
    // Divisor has to be sent byte-wise, so split here into upper/lower bytes.
    u_byte l = (u_byte)(divisor & 0xFF);
    u_byte h = (u_byte)( (divisor>>8) & 0xFF );
    // Send the frequency divisor.
    port_byte_out(0x40, l);
    port_byte_out(0x40, h);
}
References IRQ0, port_byte_out(), set_interrupt_handler(), and timer_callback().
Referenced by _start().